# Generated by Django 3.1.4 on 2021-03-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_squashed_0037_auto_20210312_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='cCdt',
            field=models.BooleanField(default=False, verbose_name='Current'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='dtlu',
            field=models.DateField(auto_now_add=True, verbose_name='Last'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='hCdt',
            field=models.BooleanField(default=False, verbose_name='Historical'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='hbu',
            field=models.BooleanField(default=False, verbose_name='Used'),
        ),
    ]
