# Generated by Django 3.1.4 on 2021-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20210320_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='mu',
            field=models.BooleanField(choices=[(True, 'Multiple'), (False, 'Single')], default=False, help_text='Defaults to profile setting', verbose_name='Multiple use'),
        ),
    ]
