# Generated by Django 3.1.4 on 2021-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20210415_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='mu',
            field=models.BooleanField(choices=[(True, 'Multiple'), (False, 'Single')], default=False, help_text='Defaults to profile setting', verbose_name='Use'),
        ),
    ]
