# Generated by Django 3.1.4 on 2021-05-11 10:37

from django.db import migrations, models

import collection.models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20210415_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.FileField(upload_to=collection.models.user_directory_path, validators=[core.validators.uploadValidator], verbose_name='Titles document / Logo file'),
        ),
    ]
