# Generated by Django 3.2.4 on 2021-07-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20210706_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(help_text='Must be unique.', max_length=100, verbose_name='Title'),
        ),
    ]
