# Generated by Django 3.1.2 on 2020-10-12 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('type', models.SmallIntegerField(choices=[(1, 'Reading'), (2, 'Critique'), (3, 'Open Mic.'), (4, 'Lit. Festival'), (5, 'Poetry Festival'), (6, 'Workshop'), (7, 'Course'), (8, 'Launch'), (9, 'Wedding'), (10, 'Wake'), (11, 'Slam'), (12, 'Celebration'), (13, 'Other')], verbose_name='type')),
                ('heldOn', models.DateField(verbose_name='held on')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readings.event', verbose_name='event')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.poem', verbose_name='poem')),
            ],
            options={
                'unique_together': {('event', 'poem')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='group')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readings.group', verbose_name='group'),
        ),
        migrations.AddField(
            model_name='event',
            name='readings',
            field=models.ManyToManyField(through='readings.Reading', to='collection.Poem'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('group', 'name', 'type', 'heldOn')},
        ),
    ]
