# Generated by Django 3.1.2 on 2020-10-12 20:09

import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='competition')),
                ('closingDate', models.DateField(verbose_name='closing date')),
                ('url', models.URLField(verbose_name='url')),
                ('access', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', editable=False, help_text='Competition access - default is public, alternative is private', max_length=7, verbose_name='access')),
                ('entryFee', models.CharField(max_length=40, verbose_name='entry fee')),
                ('prize', models.CharField(blank=True, max_length=40, verbose_name='prize')),
                ('country', models.CharField(choices=[('ARG', 'Argentina'), ('AUS', 'Australia'), ('BEL', 'Belgium'), ('CAN', 'Canada'), ('DNK', 'Denmark'), ('FIN', 'Finland'), ('FRA', 'France'), ('DEU', 'Gernmany'), ('GGY', 'Gurnesey'), ('GRC', 'Greece'), ('HKG', 'Hong Kong'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IRL', 'Ireland'), ('ITA', 'Italy'), ('JPN', 'Japan'), ('JEY', 'Jersey'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NOR', 'Norway'), ('POL', 'Poland'), ('ESP', 'Spain'), ('ZAP', 'South Africa'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('GBR', 'UK'), ('USA', 'USA')], default='GBR', max_length=3, verbose_name='country')),
                ('noOfEntries', models.PositiveSmallIntegerField(default=0, verbose_name='number of entries')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enteredOn', models.DateField(default=django.utils.timezone.now, verbose_name='entered on')),
                ('committedUntil', models.DateField(blank=True, help_text='Leave empty for the date to be calculated using the default wait days.', null=True, verbose_name='committed until')),
                ('place', models.CharField(choices=[('ukn', 'unknown'), ('unp', 'unplaced'), ('lng', 'Long listed'), ('sht', 'Short listed'), ('1st', 'First'), ('2nd', 'Secomd'), ('3rd', 'Third'), ('4th', 'Fourth'), ('5th', 'Fifth'), ('6th', 'Sixth'), ('7th', 'Seventh'), ('8th', 'Eighth'), ('9th', 'Ninth'), ('10t', 'Tenth'), ('wtdn', 'Withdrawn'), ('dltd', 'Deleted')], default='ukn', max_length=4, verbose_name='placement')),
                ('expiredOn', models.DateField(blank=True, null=True, verbose_name='expired on')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.competition', verbose_name='competition')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.poem', verbose_name='poem')),
                ('poet', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ('competition', 'poem', 'enteredOn', 'committedUntil'),
                'unique_together': {('competition', 'poem')},
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='entries',
            field=models.ManyToManyField(through='entries.Entry', to='collection.Poem'),
        ),
        migrations.AddField(
            model_name='competition',
            name='poet',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
