# Generated by Django 3.1.4 on 2021-03-20 13:53

import django.core.validators
import django.db.models.deletion
import embed_video.fields
from django.conf import settings
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    replaces = [('maintenance', '0001_initial'), ('maintenance', '0002_auto_20201118_2044'), ('maintenance', '0003_auto_20201122_1733'), ('maintenance', '0004_auto_20201124_2149'), ('maintenance', '0005_auto_20201125_1019'), ('maintenance', '0006_auto_20201125_1024'), ('maintenance', '0007_auto_20201125_1032'), ('maintenance', '0008_auto_20210112_0426'), ('maintenance', '0009_auto_20210112_0445'), ('maintenance', '0010_auto_20210122_2346'), ('maintenance', '0011_help'), ('maintenance', '0012_auto_20210128_1631'), ('maintenance', '0013_profile_pldo'), ('maintenance', '0014_auto_20210217_1550'), ('maintenance', '0015_auto_20210309_2221')]

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('collection', '0017_auto_20210122_2346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('os', models.CharField(choices=[('All', 'All'), ('Mac OS X', 'Mac OS X'), ('Windows', 'Windows'), ('Linux', 'Linux'), ('Debian', 'Debian')], max_length=8, verbose_name='OS')),
                ('type', models.SmallIntegerField(choices=[(1, 'Utility'), (2, 'Bulletin'), (3, 'ReadMe'), (4, 'Release notes')], verbose_name='Type')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('sURL', models.URLField(blank=True, max_length=255, null=True, validators=[core.validators.dropBoxExeValidator], verbose_name='Source URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='webResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(choices=[('ARG', 'Argentina'), ('AUS', 'Australia'), ('BEL', 'Belgium'), ('CAN', 'Canada'), ('DNK', 'Denmark'), ('FIN', 'Finland'), ('FRA', 'France'), ('DEU', 'Gernmany'), ('GGY', 'Gurnesey'), ('GRC', 'Greece'), ('HKG', 'Hong Kong'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IRL', 'Ireland'), ('ITA', 'Italy'), ('JPN', 'Japan'), ('JEY', 'Jersey'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NOR', 'Norway'), ('POL', 'Poland'), ('ESP', 'Spain'), ('ZAP', 'South Africa'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('GBR', 'UK'), ('USA', 'USA')], default='GBR', max_length=3, verbose_name='country')),
                ('type', models.SmallIntegerField(choices=[(1, 'Competitions'), (2, 'Magazines'), (3, 'Publishers')], verbose_name='type')),
                ('noOfUpdates', models.SmallIntegerField(default=0, help_text='number of times updated', verbose_name='#Updates')),
                ('additions', models.SmallIntegerField(default=0, help_text='additions made last update', verbose_name='#additions')),
                ('updateInterval', models.IntegerField(choices=[(0, 'none'), (1, 'next day'), (7, '1 week'), (10, '10 days'), (14, '2 weeks'), (31, '1 month'), (61, '2 months'), (91, '3 months'), (121, '4 months'), (181, '6 months'), (271, '9 months'), (365, '1 year'), (27375, 'out of UK copyright')], default=31, help_text='update period', verbose_name='interval')),
                ('refSource', models.URLField(verbose_name='reference source')),
                ('reflink', models.CharField(max_length=100, verbose_name='reference link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mmoo', models.BooleanField(choices=[(True, 'On'), (False, 'Off')], default=False, help_text='WARNING: seeting this to ON switches off the website!', verbose_name='Maintenance mode')),
                ('mmso', models.DateTimeField(blank=True, help_text='automatically updated', null=True, verbose_name='Switched at')),
                ('mmno', models.SmallIntegerField(default=1, verbose_name='Number of')),
                ('mmpd', models.CharField(choices=[('M', 'minutes'), ('H', 'hours'), ('D', 'days'), ('W', 'weeks')], default='H', max_length=1, verbose_name='Period')),
                ('mmer', models.DateTimeField(blank=True, help_text='automatically updated', null=True, verbose_name='Estimated return')),
                ('mmmg', models.CharField(blank=True, max_length=120, null=True, verbose_name='Maintenance mode message')),
                ('aumg', models.CharField(default='_NONE_', max_length=120, verbose_name='Sign on message')),
                ('vnno', models.CharField(default='0.0.5', max_length=10, verbose_name='Application Version number')),
                ('vndt', models.DateField(blank=True, null=True, verbose_name='Application Version date')),
                ('vncd', models.CharField(choices=[('δ', 'development'), ('𝛂', 'alpha testing'), ('β', 'user testing'), ('γ', 'release'), ('ζ', 'previous'), ('φ', 'patched'), ('⍵', 'emergency patch')], default='δ', max_length=1, verbose_name='Application Version candidate')),
                ('cplu', models.DateField(verbose_name='Competitions last updated')),
                ('cpui', models.SmallIntegerField(choices=[(0, 'none'), (1, 'next day'), (7, '1 week'), (10, '10 days'), (14, '2 weeks'), (31, '1 month'), (61, '2 months'), (91, '3 months'), (121, '4 months'), (181, '6 months'), (271, '9 months'), (365, '1 year'), (27375, 'out of UK copyright')], default=31, verbose_name='Competitions update interval')),
                ('mzlu', models.DateField(verbose_name='Magazines last updated')),
                ('mzui', models.SmallIntegerField(choices=[(0, 'none'), (1, 'next day'), (7, '1 week'), (10, '10 days'), (14, '2 weeks'), (31, '1 month'), (61, '2 months'), (91, '3 months'), (121, '4 months'), (181, '6 months'), (271, '9 months'), (365, '1 year'), (27375, 'out of UK copyright')], default=61, verbose_name='Magazines update interval')),
                ('pblu', models.DateField(verbose_name='Publications last updated')),
                ('pbui', models.SmallIntegerField(choices=[(0, 'none'), (1, 'next day'), (7, '1 week'), (10, '10 days'), (14, '2 weeks'), (31, '1 month'), (61, '2 months'), (91, '3 months'), (121, '4 months'), (181, '6 months'), (271, '9 months'), (365, '1 year'), (27375, 'out of UK copyright')], default=91, verbose_name='Publications update interval')),
                ('eaer', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Email admin error report')),
                ('eubr', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Email user bug fix report')),
            ],
            options={
                'verbose_name_plural': 'System parameters',
            },
        ),
        migrations.CreateModel(
            name='InformationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, default='_NONE_', max_length=100, verbose_name='Subject')),
                ('video', embed_video.fields.EmbedVideoField(help_text='[ CTRL ] + click to view', verbose_name='Video')),
                ('theOrder', models.PositiveIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Information video',
                'verbose_name_plural': 'Information video',
                'ordering': ['theOrder'],
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(max_length=100, unique=True, verbose_name='Context')),
                ('lookup', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lookup')),
            ],
            options={
                'verbose_name_plural': 'Help',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftfg', models.BooleanField(default=True, verbose_name='The first time flag')),
                ('wd4c', models.IntegerField(choices=[(0, 'none'), (1, 'next day'), (7, '1 week'), (10, '10 days'), (14, '2 weeks'), (31, '1 month'), (61, '2 months'), (91, '3 months'), (121, '4 months'), (181, '6 months'), (271, '9 months'), (365, '1 year'), (27375, 'out of UK copyright')], default=31, verbose_name='Wait period for competitions entries')),
                ('wd4s', models.IntegerField(choices=[(0, 'none'), (1, 'next day'), (7, '1 week'), (10, '10 days'), (14, '2 weeks'), (31, '1 month'), (61, '2 months'), (91, '3 months'), (121, '4 months'), (181, '6 months'), (271, '9 months'), (365, '1 year'), (27375, 'out of UK copyright')], default=181, verbose_name='Wait period for magazine submissions ')),
                ('wd4p', models.IntegerField(choices=[(0, 'none'), (1, 'next day'), (7, '1 week'), (10, '10 days'), (14, '2 weeks'), (31, '1 month'), (61, '2 months'), (91, '3 months'), (121, '4 months'), (181, '6 months'), (271, '9 months'), (365, '1 year'), (27375, 'out of UK copyright')], default=271, verbose_name='Wait period for publishers response')),
                ('dacw', models.IntegerField(default=10, help_text='Must be >=1 & <=31', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Advanced days warning of competition closure')),
                ('dfmu', models.BooleanField(choices=[(True, 'Set'), (False, 'Unset'), (None, 'Unknown')], default=False, help_text='[un]Set so that selected poems can be actioned', verbose_name='Default multiple use')),
                ('hklr', models.DateField(blank=True, editable=False, null=True, verbose_name='Last HK run on')),
                ('enct', models.IntegerField(choices=[(0, 'As input'), (1, 'Capitalise first letter'), (2, 'All lower case'), (3, 'Naturalise')], default=3, help_text='Standarise titles for consistency - applies to imported/actioned poems', verbose_name='Handle titles')),
                ('ludt', models.CharField(default='_None_', max_length=80, verbose_name='Last upload details')),
                ('wipo', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Present the current WIP poem at startup')),
                ('dbat', models.CharField(blank=True, max_length=255, null=True, verbose_name='WIP DropBox API access token')),
                ('crtx', models.CharField(blank=True, help_text='max. 35 characters', max_length=35, null=True, verbose_name='Copyright text')),
                ('cnty', models.CharField(choices=[('ARG', 'Argentina'), ('AUS', 'Australia'), ('BEL', 'Belgium'), ('CAN', 'Canada'), ('DNK', 'Denmark'), ('FIN', 'Finland'), ('FRA', 'France'), ('DEU', 'Gernmany'), ('GGY', 'Gurnesey'), ('GRC', 'Greece'), ('HKG', 'Hong Kong'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IRL', 'Ireland'), ('ITA', 'Italy'), ('JPN', 'Japan'), ('JEY', 'Jersey'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NOR', 'Norway'), ('POL', 'Poland'), ('ESP', 'Spain'), ('ZAP', 'South Africa'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('GBR', 'UK'), ('USA', 'USA')], default='GBR', max_length=3, verbose_name='country preference')),
                ('rbfr', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='recieve bug fix reports')),
                ('dfpf', models.ForeignKey(default=1, help_text='Applies to imported/actioned poems - can be left blank if unknown', on_delete=django.db.models.deletion.CASCADE, to='collection.poeticform', verbose_name='Default poetic form')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wipp', models.ForeignKey(blank=True, limit_choices_to={'wip': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.poem', verbose_name='Current WIP poem')),
                ('pldo', models.IntegerField(choices=[(1, 'Candidate & Used flags'), (2, 'Entries, Submissions, Publishing & Readings numbers')], default=1, verbose_name='poem listing display options')),
                ('abtg', models.CharField(default='_Assigned_', max_length=50, verbose_name='Assigned batch tag')),
                ('dutg', models.CharField(default='_Upload_', help_text='Automatically given to uploaded & imported poems', max_length=50, verbose_name='Default upload tag')),
            ],
        ),
    ]
