# Generated by Django 3.1.4 on 2021-03-21 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20210320_1348'),
        ('maintenance', '0001_squashed_0015_auto_20210309_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wipp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection.poem', verbose_name='Current WIP poem'),
        ),
    ]
