# Generated by Django 3.1.4 on 2021-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20210321_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dfmu',
            field=models.BooleanField(choices=[(True, 'Multiple'), (False, 'Single')], default=False, help_text='[un]Set so that selected poems can be actioned', verbose_name='Default multiple use'),
        ),
    ]
