# Generated by Django 3.1.4 on 2021-04-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20210415_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dfmu',
            field=models.BooleanField(choices=[(True, 'Multiple'), (False, 'Single')], default=False, help_text='Sets either single or multiple use of a poem', verbose_name='Default use'),
        ),
    ]
