# Generated by Django 3.1.4 on 2021-05-06 20:31

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20210415_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemparameters',
            name='logo',
            field=models.URLField(blank=True, help_text='Must be a dropbox link to jpg/png - max size 124x124px.  Shift-click to access', max_length=255, null=True, validators=[core.validators.dropBoxDocValidator], verbose_name='Source URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cnty',
            field=models.CharField(choices=[('ALL', 'All'), ('ARG', 'Argentina'), ('AUS', 'Australia'), ('BEL', 'Belgium'), ('CAN', 'Canada'), ('DNK', 'Denmark'), ('FIN', 'Finland'), ('FRA', 'France'), ('DEU', 'Gernmany'), ('GGY', 'Gurnesey'), ('GRC', 'Greece'), ('HKG', 'Hong Kong'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IRL', 'Ireland'), ('ITA', 'Italy'), ('JPN', 'Japan'), ('JEY', 'Jersey'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NOR', 'Norway'), ('POL', 'Poland'), ('ESP', 'Spain'), ('ZAP', 'South Africa'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('GBR', 'UK'), ('USA', 'USA')], default='GBR', max_length=3, verbose_name='country preference'),
        ),
        migrations.AlterField(
            model_name='webresource',
            name='country',
            field=models.CharField(choices=[('ALL', 'All'), ('ARG', 'Argentina'), ('AUS', 'Australia'), ('BEL', 'Belgium'), ('CAN', 'Canada'), ('DNK', 'Denmark'), ('FIN', 'Finland'), ('FRA', 'France'), ('DEU', 'Gernmany'), ('GGY', 'Gurnesey'), ('GRC', 'Greece'), ('HKG', 'Hong Kong'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IRL', 'Ireland'), ('ITA', 'Italy'), ('JPN', 'Japan'), ('JEY', 'Jersey'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NOR', 'Norway'), ('POL', 'Poland'), ('ESP', 'Spain'), ('ZAP', 'South Africa'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('GBR', 'UK'), ('USA', 'USA')], default='GBR', max_length=3, verbose_name='country'),
        ),
    ]
