# Generated by Django 3.1.4 on 2021-05-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_auto_20210507_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logo',
        ),
    ]
