# Generated by Django 3.1.4 on 2021-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20210507_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uslo',
            field=models.BooleanField(choices=[(True, 'hummingBird'), (False, 'personal')], default=True, verbose_name='choice'),
        ),
    ]
