# Generated by Django 3.1.4 on 2021-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_profile_uslo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loch',
            field=models.SmallIntegerField(choices=[(0, 'hummingBird'), (1, 'personal'), (2, 'none')], default=0, verbose_name='logo choice'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uslo',
            field=models.BooleanField(default=False),
        ),
    ]
