# Generated by Django 3.1.4 on 2021-05-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_auto_20210509_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='uslo',
        ),
    ]
