# Generated by Django 3.1.4 on 2021-05-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_remove_profile_uslo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='loch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='logo',
        ),
    ]
