# Generated by Django 3.1.4 on 2021-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_auto_20210509_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lgch',
            field=models.SmallIntegerField(choices=[(0, 'hummingbird'), (1, 'personal'), (2, 'none')], default=0, verbose_name='Logo choice'),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Personal logo file'),
        ),
    ]
