# Generated by Django 3.1.4 on 2021-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_auto_20210510_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Personal logo file'),
        ),
    ]
