# Generated by Django 3.2.4 on 2021-09-16 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0019_delete_downloadresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'Utility'), (2, 'Bulletin'), (3, 'ReadMe'), (4, 'Release notes'), (5, 'Category update')], verbose_name='Type')),
                ('description', models.CharField(max_length=80, verbose_name='Description')),
                ('os', models.CharField(choices=[('All', 'All'), ('Mac OS X', 'Mac OS X'), ('Windows', 'Windows'), ('Linux', 'Linux'), ('Debian', 'Debian')], max_length=8, verbose_name='OS')),
                ('file', models.FilePathField(path=maintenance.models.user_directory_path, verbose_name='File')),
                ('poet', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
