# Generated by Django 3.1.4 on 2021-03-01 19:24

import isbn_field.fields
import isbn_field.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=isbn_field.fields.ISBNField(blank=True, default='', max_length=17, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
    ]
