"""
Django settings for hummingbird3 project.

Last updated:
    15-Jan-21 Added websites menu options
                    Where is ... ? and GDPR & ePR popup modal forms
    15-May-21 Added CKEDITOR for Notes

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured


#=================GET ENVIRONMENT VARIABLES ROUTINE================
def get_env_variable(var_name):
    try:
        return os.environ[var_name]
    except KeyError:
        error_msg='Set the {} environment variable!'.format(var_name)
        raise ImproperlyConfigured(error_msg)
#=================GET ENVIRONMENT VARIABLES========================

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'm!*ux8npv#skjawp$n4%6-@x2^v+yw&1p+k8l_)rj1cg-4lru#'
SECRET_KEY=get_env_variable('HB3_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '192.168.1.248', '192.168.1.211','localhost','orac.local']
# ALLOWED_HOSTS=['*']

# needed for debug toolbar
INTERNAL_IPS = [
    '127.0.0.1','192.168.1.248','192.168.1.211','orac.local',
]

SITE_ID = 1

HB_WEB_SITE="file:///Users/jr/adv/hb3/hummingBird/___Help_/"

# Application definition

INSTALLED_APPS = [

    'django.contrib.contenttypes',
    'baton',
    'django.contrib.admin',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admindocs',
    'cuser',
    'django_userforeignkey',
    'maintenance_mode',
    'debug_toolbar',
    'django_user_agents',
    'django_extensions',
    'contactus',
    'error_report',
    'embed_video',
    'adminsortable2',
    'mptt',
    'django_mptt_admin',
    'isbn_field',
    'ckeditor',
    'ckeditor_uploader',
    'taggit',

    'collection',
    'maintenance',
    'entries',
    'submissions',
    'publishing',
    'readings',

    'baton.autodiscover',
]

DEFAULT_AUTO_FIELD='django.db.models.AutoField'

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cuser.middleware.CuserMiddleware',
    'django_userforeignkey.middleware.UserForeignKeyMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware',
    'error_report.middleware.ExceptionProcessor',
    'django_user_agents.middleware.UserAgentMiddleware',

]

# Provider specific settings
# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         # For each OAuth based provider, either add a ``SocialApp``
#         # (``socialaccount`` app) containing the required client
#         # credentials, or list them here:
#         'APP': {
#             'client_id': '123',
#             'secret': '456',
#             'key': ''
#         }
#     }
# }


ROOT_URLCONF = 'hummingbird3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'maintenance_mode.context_processors.maintenance_mode',
            ],
        },
    },
]


AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'hummingbird3.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql_psycopg2',
        'NAME':     'hb3',
        'USER':      get_env_variable('HB3_DB_USER'),
        'PASSWORD':  get_env_variable('HB3_DB_PASSWORD'),
        'HOST':     'LOCALHOST',
        'PORT':     '5432',
    }
}

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': '127.0.0.1:11211',
#     }
# }
#
# USER_AGENTS_CACHE = 'default'


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-GB'

TIME_ZONE = 'GB'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATETIME_FORMAT = 'Y-M-d H:i:s'
DATE_FORMAT = 'Y-M-d'
FORMAT_DATETIME ='%Y-%b-%d at %H:%M:%S'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= BASE_DIR / STATIC_URL
STATICFILES_DIRS=[os.path.join(BASE_DIR,"static")]
STATICFILES_DIR=STATICFILES_DIRS[0]
IMAGES_DIR=os.path.join(STATIC_ROOT,'_images')
LOGO=os.path.join(IMAGES_DIR,'hb3_SMALL_ICON.png')
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


# ============  DJANGO CONSTANTS =============================
# controls to number of records appearing on a change_list page
# use list_per_page=settings.LIST_PER_PAGE in admin class to
# override the default of 100
LIST_PER_PAGE=25

# ============  TAGGIT CONSTANTS =============================

TAGGIT_CASE_INSENSITIVE = True

# ============ ckeditor configuration =======================

CKEDITOR_DIR = os.path.join(STATIC_ROOT,'ckeditor')
CKEDITOR_BASEPATH = os.path.join(CKEDITOR_DIR,'ckeditor')
INITIAL_POEM_DRAFT = os.path.join(CKEDITOR_DIR,'initialPoemDraft.html')

CKEDITOR_RESTRICT_BY_USER=True
CKEDITOR_BROWSE_SHOW_DIRS=True
CKEDITOR_RESTRICT_BY_DATE=True

CKEDITOR_UPLOAD_PATH  = 'utils.get_notes_filepath'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar':  'full',
        'skin':     'moono-lisa',
        'height':   500,
        'width':    '100%',
        'uiColor':  '#CCEAEE',
    },
}



# ============ hummingBird application Constants ============

THE_ADMIN_ID=1
THE_DEMO_ID=2
REGULAR_USER_GROUP=1
SUPER_GROUP=2
# READ_ONLY_GROUP
DEMO_GROUP=3
MULTIPLE_USE_OVERRIDE=chr(178) # ² two superscript
SINGLE_USE_OVERRIDE=chr(185)   # ¹ one superscript

#=========== Maintenance mode ===================
# if True the ability to switch maintenance-mode on & off will be activated
MAINTENANCE_MODE = None

# if True the superuser will not see the maintenance-mode page
MAINTENANCE_MODE_IGNORE_SUPERUSER = False

# if True the maintenance mode will not return 503 response while running tests
# useful for running tests while maintenance mode is on, before opening the site to public use
MAINTENANCE_MODE_IGNORE_TESTS = False

# the template that will be shown by the maintenance-mode page
MAINTENANCE_MODE_TEMPLATE = '503.html'

# the HTTP status code to send
MAINTENANCE_MODE_STATUS_CODE = 503

# the value in seconds of the Retry-After header during maintenance-mode
MAINTENANCE_MODE_RETRY_AFTER = 3600 # 1 hour

#=========== Contact us email ===================

CONTACT_US_EMAIL='jaywarr@mac.com'

#========== Email ===================================

# EMAIL_HOST='smtp.gmail.com'
# EMAIL_HOST_USER='hummingbirdpoet0@gmail.com'
# EMAIL_HOST_PASSWORD=get_env_variable('HB3_EMAIL_PASSWORD')
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_SUBJECT_PREFIX='[hummingbird] '
# EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
# ONLY for development/testing uses console
EMAIL_BACKEND='django.core.mail.backends.console.EmailBackend'

#========== Error report ===================================
ERROR_DETAIL_SETTINGS = {
    "ERROR_DETAIL_ENABLE": True,
    "ERROR_DETAIL_HEIGHT": 333,
}

# ============ allauth config settings ===============

# Custom allauth settings
# Use email as primary identification

ACCOUNT_AUTHENTICATION_METHOD='email'
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS=3
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[hummingBird] '
ACCOUNT_UNIQUE_EMAIL = True
# make email mandatory to avoid junk email accounts
ACCOUNT_EMAIL_VERIFICATION='mandatory'
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE=True
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION = True
ACCOUNT_PASSWORD_MIN_LENGTH = 8
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_USERNAME_MIN_LENGTH=2
ACCOUNT_LOGIN_ATTEMPTS_LIMIT=5
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT=86400
ACCOUNT_LOGOUT_REDIRECT_URL = "/accounts/login/"

LOGIN_REDIRECT_URL='/admin/collection/poem/'

# ============ Help =================================

HELP_SUBSITUTE_FOR_NUMBERS='~'
HELP_DIR="_help_/"
HELP_URL_PREFIX=HB_WEB_SITE+HELP_DIR

# ============ Mptt =================================

MPTT_ADMIN_LEVEL_INDENT = 40

#========== Baton ===================================

BATON_VERSION='2.1.5'

LOGIN_REDIRECT_URL='/admin/collection/poem/'

help_modal = '''
modalContent = `
    <div>
        <p><strong style="font-weight: 900">Information</strong></p>
        <p>General, overview, and how-to information is provided in a series of YouTube instructional videos. As a minimum you should 
          view the Introduction video to gain an overall appreciation of the application's capabilities and functionality. 
          You can access all these videos by clicking on the&nbsp;&nbsp;<i class="fa fa-info" style="color:dimgray"></i>&nbsp;&nbsp;icon at the bottom of the screen
          or the same icon under the <b><i>Maintenance</i></b> menu.
        </p>
        <p><strong style="font-weight: 900">Help</strong></p>modal
        <p>Detailed help and support is provided via in-line, context sensitive, web pages. 
          You can access all these pages by clicking on the&nbsp;&nbsp;<i class="fa fa-heading" style="color:dimgray"></i>&nbsp;&nbsp;icon at the bottom of the screen.
        </p>
        <p><strong style="font-weight: 900">Contact</strong></p>
        <p>You can contact hummingbird admin at any time by email. 
        Click on the&nbsp;&nbsp;
        <i class="fa fa-paper-plane" style="color:dimgray"></i>&nbsp;&nbsp;icon at the bottom of the screen. 
        </p>
        <p><strong style="font-weight: 900">Bugs Issues & RFIs</strong></p>
        <p>Most bugs, problems, glitches and application malfunctions are automatically captured and logged for attention by hummingbird admin. 
        However, you are encouraged to report any operational problems, issues and make RFIs (requests for improvement) via the contact page.
        </p>
    </div>
`;
modal = new Baton.Modal({
    title: 'Where is ... ?',
    content: modalContent,
});
modal.open();
'''

acceptCookies_modal = '''
modalContent = `
    <div>
        <p><strong style="font-weight: 900">Accept cookies</strong></p>
        <p>This application web-site uses cookies and various web technologies.
           Their use is compliant and consistent with the General Data Protection Regulation 
           (GDPR) and ePrivacy Directive (ePR).
            You can consent to the use of such technologies by closing this notice
           and by interacting with any of the application's links, menus or buttons.
        </p>
        <p><strong style="font-weight: 900">Don't accept cookies</strong></p>
        <p style="color:red">If you are uncomfortable, or are not assured, by the
                             preceeding statements you should stop using the application now.</p>
        <p><strong style="font-weight: 900">Informed consent</strong></p>
        <p style="color:blue">To be clear: your continued use will be taken as informed consent.</p>
    </div>
`;
modal = new Baton.Modal({
    title: 'GDPR and ePR notice',
    content: modalContent,
});
modal.open();
'''

demoWarning_modal = '''
modalContent = `
    <div>
        <p><strong style="font-weight: 900">Demo warning</strong></p>
        <p>You attempted to ???</p>
        <p> As a Demo user you are <b>not permitted</b> to:
        <ul>
            <li>add/create an item</li>
            <li>change an item</li>
            <li>delete an item</li>
            <li>complete an action on a set of items</li>           
        </ul>   
        </p>
    </div>
`;
modal = new Baton.Modal({
    title: 'demoWarning',
    content: modalContent,
});
modal.open();
'''

BATON = {
    'SITE_HEADER':                      '<img src="/static/_images/hummingbird_thoughtshift_04_SMALL.png" />',
    'SITE_TITLE':                       'hummingbird',
    'INDEX_TITLE':                      'Administration',
    'SUPPORT_HREF':                     'https://github.com/otto-torino/django-baton/issues',
    'COPYRIGHT':                        '<a href="https://www.secretartybird.info">copyright © 2021 IMPpress</a>',
    'POWERED_BY':                       '<a href="https://www.otto.to.it">jay Arr</a>',
    'CONFIRM_UNSAVED_CHANGES':          True,
    'SHOW_MULTIPART_UPLOADING':         True,
    'ENABLE_IMAGES_PREVIEW':            True,
    'CHANGELIST_FILTERS_IN_MODAL':      True,
    'CHANGELIST_FILTERS_ALWAYS_OPEN':   False,
    'CHANGELIST_FILTERS_FORM':          True,
    'COLLAPSABLE_USER_AREA':            True,
    'MENU_ALWAYS_COLLAPSED':            True,
    'MENU_TITLE':                       'Menu',
    'MESSAGES_TOASTS':                  True,
    'GRAVATAR_DEFAULT_IMG':             'identicon',
    'LOGIN_SPLASH':                     '/static/_images/multicolored-rainbow-background.jpg',
    'SEARCH_FIELD': {
        'label': 'Search poems/poets/wiki ...',
        'url': '/admin/search/',
                    },
    'MENU': (
        { 'type': 'title', 'label': 'System', 'apps': ('auth', 'error_report', ),},
        {
            'type': 'app',
            'name': 'auth',
            'label': 'Authentication',
            'icon': 'fa fa-user-check fa-2x',
            'default_open': False,
            'models': (
                {
                    'name': 'user',
                    'label': 'Users',
                    'icon': 'fa fa-user',
                },
                {
                    'name': 'group',
                    'label': 'Groups',
                    'icon': 'fa fa-users',
                },
            )
        },

        {
            'type': 'app',
            'name': 'error_report',
            'label': 'Error reports',
            'icon': 'fa fa-file-excel fa-2x',
            'default_open': False,
            'models': (
                {'name': 'error', 'label': 'Bugs', 'icon': 'fa fa-bug'},
                {'name': 'bfp', 'label': 'Fix progress', 'icon': 'fa fa-tasks'}
            )
        },


        { 'type': 'title', 'label': 'application', 'apps': ('collection', 'entries','submissions', 'publishing', 'readings', 'maintenance', ),
                'default_open': False,},
        {
            'type': 'app',
            'name': 'collection',
            'label': 'Collection',
            'icon': 'fa fa-copy fa-2x',
            'default_open': False,
            'models': (
                { 'name': 'poem',       'label': 'Poems',       'icon': 'fa fa-file-signature'},
                { 'name': 'note',       'label': 'Notes',       'icon': 'fa fa-sticky-note'},
                { 'name': 'link',       'label': 'Links',       'icon': 'fa fa-link'},
                { 'name': 'category',   'label': 'Categories',  'icon': 'fa fa-sitemap'},
                { 'name': 'upload',     'label': 'Uploads',     'icon': 'fa fa-file-upload'},
                { 'name': 'poeticform', 'label': 'Poetic forms','icon': 'fa fa-align-justify'},
            )
        },
        {
            'type': 'app',
            'name': 'entries',
            'label': 'Entries',
            'icon': 'fa fa-envelope fa-2x',
            'default_open': False,
            'models': (
                {'name': 'competition', 'label': 'Competitions',  'icon': 'fa fa-sort-numeric-down'},
                {'name': 'entry',       'label': 'Entries',       'icon': 'fa fa-envelope-open-text'},
            )
        },
        {
            'type': 'app',
            'name': 'submissions',
            'label': 'Submissions',
            'icon': 'fa fa-share fa-2x',
            'default_open': False,
            'models': (
                {'name': 'magazine',   'label': 'Magazines',   'icon': 'fa fa-chart-bar'},
                {'name': 'submission', 'label': 'Submissions', 'icon': 'fa fa-paper-plane'},
            )
        },
        {
            'type': 'app',
            'name': 'publishing',
            'label': 'Publishing',
            'icon': 'fa fa-book-open fa-2x',
            'default_open': False,
            'models': (
            {'name': 'publisher',   'label': 'Publisher & publications', 'icon': 'fa fa-user-check'},
            {'name': 'publication', 'label': 'Publications & content',   'icon': 'fa fa-clone' },
            # {'name': 'content', 'label': 'Content', 'icon':  'fa fa-file-alt' },
            )
        },
        {
            'type': 'app',
            'name': 'readings',
            'label': 'Performances',
            'icon': 'fa fa-microphone fa-2x',
            'default_open': False,
            'models': (
            {'name': 'group', 'label': 'Groups', 'icon': 'fa fa-user-friends'},
            {'name': 'event', 'label': 'Events', 'icon': 'fa fa-calendar-check'},
            {'name': 'reading', 'label': 'Reading', 'icon': 'fa fa-book-reader'},
            )
        },
        {
            'type': 'app',
            'name': 'maintenance',
            'label': 'Maintenance',
            'icon': 'fa fa-cogs fa-2x',
            'default_open': False,
            'models': (
                {'name': 'profile',          'label':   'Profile',            'icon':       'fa fa-user-cog'},
                {'name': 'download',         'label':   'Download',           'icon':       'fa fa-download'},
                {'name': 'webresource',      'label':   'Web resource',       'icon':       'fa fa-link' },
                {'name': 'systemparameters', 'label': 'System parameters',    'icon':       'fa fa-cog'},
                #  ====  re-assigned regular user access to footnote icons - only superusers can see these menu entries ====
                {'name': 'informationvideo', 'label':   'Information',        'icon':       'fa fa-info'},
                {'name': 'help',             'label':   'help',               'icon':       'fa fa-question-circle'},
            )
        },
        {
            'type': 'title',
            'label': 'Resources',
            'default_open': False,
            'children': [
                {'type': 'free', 'label': 'About', 'url': 'http://www.secretarybird.info/_Help_/About.html', 'icon': 'fa fa-asterisk'},
                {'type': 'free', 'label': 'Where is ...', 'url': 'javascript:%s' % help_modal,'icon': 'fa fa-question'},
                {'type': 'free', 'label': 'GDPR & ePR notice', 'url': 'javascript:%s' % acceptCookies_modal, 'icon': 'fa fa-exclamation'},
                {'type': 'free', 'label': 'Dictionary', 'url': 'https://en.wiktionary.org/wiki/Wiktionary:Main_Page', 'icon': 'fa fa-spell-check'},
                {'type': 'free', 'label': 'Compare', 'url': 'https://www.diffchecker.com', 'icon': 'fa fa-compress-alt'},
                {'type': 'free', 'label': 'Gig guide', 'url': 'https://www.writeoutloud.net/events/', 'icon': 'fa fa-comment-dots'},
                # {'type': 'free', 'label': 'Google', 'url': 'https://www.google.com/', 'icon': 'fa fa-angle-double-left'},
                {'type': 'free', 'label': 'RSS feeds', 'url': 'https://poet.com/rss/pr', 'icon': 'fa fa-rss'},
            ]
        },
        {
            'type':  'title',
            'label': 'Websites',
            'default_open': False,
            'children': [
                {'type': 'free', 'label': 'The Poetry Society',         'url': 'https://poetrysociety.org.uk',              'icon': 'fa fa-bookmark'},
                {'type': 'free', 'label': 'The Poetry Book Society',    'url': 'https://www.poetrybooks.co.uk',             'icon': 'fa fa-book-open'},
                {'type': 'free', 'label': 'poet DG',                    'url': 'http://www.dawngorman.co.uk',               'icon': 'fa fa-user-edit'},
                {'type': 'free', 'label': 'Poetry Super Highway',       'url': 'https://www.poetrysuperhighway.com/psh/',   'icon': 'fa fa-road'},
                {'type': 'free', 'label': 'Hedgehog Poetry Press',      'url': 'https://www.hedgehogpress.co.uk',           'icon': 'fa fa-book'},
            ]
        }
    ),
}
